# Generated by Django 4.0.6 on 2022-07-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_basemodel_college_course_faculty_marksheet_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_Id',
            new_name='login_id',
        ),
    ]
